PurBeurre/urls.py
from django.contrib import admin
from django.urls import path, include

from comparator import views

urlpatterns = [
    path('site_admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('comparator/', include('comparator.urls', namespace='comparator')),
    path('user/', include('user.urls', namespace='user')),
]

comparator/urls.py
"""Here are all the urls used for comparator app"""


from django.conf.urls import url
from . import views


app_name = 'comparator'

urlpatterns = [
    url(r'^search/$', views.search, name="search"),
    url(r'^(?P<bar_code>[0-9]+)/$', views.detail, name="detail"),
    url(r'^substitute/$', views.substitute, name="substitute"),
    url(r'^save_sub/$', views.save_sub, name="save_sub"),
    url(r'^favourites/$', views.favourites, name="favourites"),
    url(r'^terms/$', views.terms, name="terms"),
    url(r'^delete_sub/$', views.delete_sub, name="delete_sub"),
]

user/urls.py
"""Here are all urls used in user app"""

from django.conf.urls import url
from . import views


app_name = 'user'

urlpatterns = [
    url(r'^create/$', views.create_user, name="create_user"),
    url(r'^connexion/$', views.connexion, name="connexion"),
    url(r'^logout/$', views.logout_user, name="logout"),
    url(r'^account/$', views.account, name="account"),
]

comparator/models.py
"""Here are models user to create the deatabase"""


from django.db import models
from django.contrib.auth.models import User


class Category(models.Model):
    """Category model (all the different categories for food)"""
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name

class Food(models.Model):
    """Food model, here will be store all food items"""
    code = models.CharField(max_length=13, unique=True, primary_key=True)
    name = models.CharField(max_length=100)
    nutriscore = models.CharField(max_length=1)
    fat = models.DecimalField(max_digits=6, decimal_places=2, null=True)
    salt = models.DecimalField(max_digits=6, decimal_places=2, null=True)
    saturated_fat = models.DecimalField(max_digits=6, decimal_places=2, null=True)
    sugars = models.DecimalField(max_digits=6, decimal_places=2, null=True)
    pict = models.URLField()
    off_url = models.URLField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    user = models.ManyToManyField(User, related_name='food', blank=True)


    def __str__(self):
        return self.name

comparator/forms.py
"""Here are forms used in comparator app"""


from django import forms

class SearchForm(forms.Form):
    """Form which permit to user to search for a food item"""
    search_widget = forms.TextInput(attrs={'placeholder': 'Aliment...', 'class': 'input-xl'})
    user_input = forms.CharField(label='', max_length=50, widget=search_widget)

comparator/views.py
"""Here are all the views we use in the Comparator app"""


from django.shortcuts import render, reverse, get_object_or_404
from django.http import HttpResponseRedirect
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.contrib.auth.models import User
from .forms import SearchForm
from .models import Food


def index(request):
    """Display index page"""

    form = SearchForm()
    return render(request, 'comparator/index.html', {'form': form})


def search(request):
    """Send search form request and return results"""

    query = request.GET.get('user_input')
    # We filter into tthe db items which name contains user input
    result_list = Food.objects.filter(name__icontains=query).order_by('code')
    # Adding paginator in order to have 9 results per page
    paginator = Paginator(result_list, 9)
    page = request.GET.get("page")

    try:
        food = paginator.page(page)
    except PageNotAnInteger:
        food = paginator.page(1)
    except EmptyPage:
        food = paginator.page(paginator.num_pages)

    context = {
        "user_input": query,
        "food": food,
        "paginate": True
    }

    return render(request, 'comparator/search.html', context)


def detail(request, bar_code):
    """Display detail page"""

    # If item does not exist, display 404 page
    food = get_object_or_404(Food, code=bar_code)

    context = {
        "food": food
    }

    return render(request, 'comparator/detail.html', context)


def substitute(request):
    """Display substitute page form user product choice"""

    query = request.GET.get('user_substitute')
    # If item does not exist, display 404 page
    user_choice = get_object_or_404(Food, code=query)
    choice_cat = user_choice.category_id
    # Ordering items by nutriscore, in order to find best ones
    full_list = Food.objects.filter(category_id=choice_cat).order_by('nutriscore')
    sub_dic = {}
    # Iterating to have 9 results
    for item in full_list:
        if len(sub_dic) <= 8:
            user = request.user
            # Checking if items is already added as favourite for authenticated user
            if len(item.user.filter(username=user.username)) != 0:
                sub_dic[item] = True
            else:
                sub_dic[item] = False

        else:
            break

    context = {
        "subdic": sub_dic,
        "query": user_choice,
    }

    return render(request, 'comparator/substitute.html', context)

def save_sub(request):
    """Saving substitutes as favourites"""

    if request.user.is_authenticated:
        query_code = request.GET.get('query_code')
        sub_code = request.GET.get('sub_code')
        sub = Food.objects.get(code=sub_code)
        request.user.food.add(sub)

        return HttpResponseRedirect('/comparator/substitute/?user_substitute={}'.format(query_code))

    else:
        return HttpResponseRedirect(reverse('user:connexion'))

def delete_sub(request):
    """Deleting substitute from favourites"""
    if request.user.is_authenticated:
        if 'sub_code' in request.GET:
            # Deleting favourite sub form favourites template
            sub_code = request.GET.get('sub_code')
            sub = Food.objects.get(code=sub_code)
            request.user.food.remove(sub)

            return HttpResponseRedirect(reverse('comparator:favourites'))

        else:
            # Deleting favourite sub from substitute template
            query_code = request.GET.get('query_code')
            sub_code = request.GET.get('del_sub')
            sub = Food.objects.get(code=sub_code)
            request.user.food.remove(sub)

            return HttpResponseRedirect('/comparator/substitute/?user_substitute={}'.format(query_code))

    else:
        return HttpResponseRedirect(reverse('user:connexion'))


def favourites(request):
    """User can see all his saved favourites"""

    if request.user.is_authenticated:
        user = request.user
        sub_list = user.food.all().order_by('nutriscore')
        paginator = Paginator(sub_list, 9)
        page = request.GET.get("page")

        try:
            sublist = paginator.page(page)
        except PageNotAnInteger:
            sublist = paginator.page(1)
        except EmptyPage:
            sublist = paginator.page(paginator.num_pages)


        context = {
            "sublist": sublist
        }

        return render(request, 'comparator/favourites.html', context)

    else:
        return HttpResponseRedirect(reverse('user:connexion'))


def terms(request):
    """The view display terms os use"""
    return render(request, 'comparator/terms.html')

comparator/templates/comparator/account.html
{% extends 'comparator/base.html' %}
{% load static %}

{% block content %}

<header class="masthead-mini account-img">
  <div class="container h-100">
    <div class="row h-100 align-items-center justify-content-center text-center">
      <div class="col-lg-10 align-self-center">
        <h1 class="text-uppercase text-white font-weight-bold">Bonjour</h1>
        <h1 class="text-uppercase text-white font-weight-bold">{{ request.user }}</h1>
      </div>
    </div>
  </div>
</header>

<!-- About Section -->
<section class="page-section bg-account sect-h-100">
  <div class="container h-100">
    <div class="row justify-content-center">
      <div class="col-lg-8 text-center">
        <h4 class="text-uppercase text-white font-weight-bold">Votre adresse email : {{ request.user.email }}</h4>
      </div>
    </div>
    <div class='space-bot'></div>
    <div class="row justify-content-center">
      <form method="post">
        {% csrf_token %}
        {{ form }}
      <button type="submit" id="submit-button" class="search-button btn btn-primary btn-xl js-scroll-trigger">Modifier</button>
    </form>
    </div>
  </div>
</section>

{% endblock %}

comparator/templates/comparator/base.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Creative - Start Bootstrap Theme</title>

  {% load static %}

  <!-- Font Awesome Icons -->
  <link href="{% static 'comparator/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet">
  <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic' rel='stylesheet' type='text/css'>
  <link href="http://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet" type="text/css">
  <link href="http://fonts.googleapis.com/css?family=Scope+One" rel="stylesheet" type="text/css">

  <!-- Plugin CSS -->
  <link href="{% static 'comparator/vendor/magnific-popup/magnific-popup.css' %}" rel="stylesheet">

  <!-- Theme CSS - Includes Bootstrap -->
  <link href="{% static 'comparator/css/creative.css' %}" rel="stylesheet">
  <link href="{% static 'comparator/css/purbeurre.css' %}" rel="stylesheet">

</head>

<body id="page-top">

    <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
    <div class="container">
      <a class="navbar-brand js-scroll-trigger" href="/"><img class="nav-logo" src="{% static 'comparator/img/logo_pur_beurre.png' %}" alt="Logo de Pur Beurre"></a>
      <a class="navbar-brand js-scroll-trigger" href="/">Pur Beurre</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto my-2 my-lg-0">
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger">
              <form method='get' action="{% url 'comparator:search' %}">
                {% csrf_token %}
                <input type="text" name="user_input" placeholder="Aliment...">
                <button type="submit" class=""><i class="nav-icons fas fa-search"></i></button>
              </form>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger">{{ request.user }}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{% url 'user:account' %}">
              <i class="nav-icons fas fa-user-alt"></i>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{% url 'comparator:favourites' %}">
              <i class="nav-icons fas fa-carrot"></i>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{% url 'user:logout' %}">
              <i class="nav-icons fas fa-sign-out-alt"></i>
            </a>
          </li>
          {% else %}
           <li class="nav-item">
            <a class="nav-link js-scroll-trigger">
              <form method='get' action="{% url 'comparator:search' %}">
                {% csrf_token %}
                <input type="text" name="user_input" placeholder="Aliment...">
                <button type="submit" class=""><i class="nav-icons fas fa-search"></i></button>
              </form>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{% url 'user:connexion' %}">
              <i class="nav-icons fas fa-user-alt"></i>
            </a>
          </li>
          {% endif %}

        </ul>
      </div>
    </div>
  </nav>

  {% block content %}{% endblock %}

  <!-- Footer -->
  <footer class="bg-light py-5">
    <div class="container">
      <div class="row">
        <div class="col-lg-6 small text-center"><a class="footer-text" href="{% url 'comparator:terms' %}">Mentions légales</a></div>
        <div class="col-lg-6 small text-center"><a class="footer-text" href="{% url 'index' %}#contact">Contact</a></div>
      </div>
    </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'comparator/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'comparator/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Plugin JavaScript -->
  <script src="{% static 'comparator/vendor/jquery-easing/jquery.easing.min.js' %}"></script>
  <script src="{% static 'comparator/vendor/magnific-popup/jquery.magnific-popup.min.js' %}"></script>

  <!-- Custom scripts for this template -->
  <script src="{% static 'comparator/js/creative.min.js' %}"></script>

</body>

</html>

comparator/templates/comparator/create_user.html
{% extends 'comparator/base.html' %}
{% load static %}

{% block content %}

<header class="masthead connect-img">
  <div class="container h-100">
    <div class="row h-100 align-items-center justify-content-center text-center">
      <div class="col-lg-10 align-self-end">
        <h1 class="text-uppercase text-white font-weight-bold">Création de compte utilisateur</h1>
        <hr class="divider my-4">
      </div>
      <div class="col-lg-8 align-self-baseline">
        <form method="post">
          {% csrf_token %}
          <ul class="connect-list">
            {{ form.as_ul }}
          	<li class="connect-list-row"><button type="submit" class="mytest btn btn-primary btn-xl js-scroll-trigger">Valider</button></li>
          </ul>
        </form>
      </div>
    </div>
  </div>
</header>

{% endblock %}

comparator/templates/comparator/favourites.html
{% extends 'comparator/base.html' %}
{% load static %}

{% block content %}

<section class="page-section-7 fav-bg">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-8 text-center">
        <h2 class="text-white mt-0 food-name" id="user_query">Vos favoris</h2>
      </div>
    </div>
  </div>
</section>

<section class="page-section bg-beige sect-h-100">
  <div class="container h-0">
    {% if sublist|length_is:"0" %}
    	<h4 class="text-uppercase text-center text-white font-weight-bold">Vous n'avez aucun favori enregistré</h4>
    {% else %}
    <div class="container">
	    <div class="row">
		  {% for item in sublist %}
			  <div class="col-sm-4 text-center food-item-box"><span class="nutriscore" data-score="{{ item.nutriscore }}">{{ item.nutriscore }}</span>
			  	<div class="food-item">
			  	  <div style="background-image: url('{{ item.pict }}');background-size: cover;background-position: 0px 50%;height: 85%;border-top-left-radius: 5px;border-top-right-radius: 5px;"></div>
			  	  <button class="subs-button2 btn btn-primary btn-xl cap-text" onclick="window.location.href = '{% url 'comparator:detail' bar_code=item.code %}';">{{ item.name }}</button>
			  	  <form method="get" action="{% url 'comparator:delete_sub' %}">
			  	  	<input type="text" name="sub_code" class="hidden-field" value="{{ item.code }}">
				  	<button type="submit" id="func-test" class="subs-button btn btn-primary btn-xl cap-text">Supprimer des favoris</button>
				  </form>
			    </div>
			  </div>
		  {% endfor %}
	    </div>
	</div>
    {% endif %}
      <div class="clearfix"></div>

    {% if sublist.has_other_pages %}
	  <ul class="pagination">
	    {% if sublist.has_previous %}
	      <li class="paginate-inactive"><a class="text-white" href="?&page={{ sublist.previous_page_number }}">&laquo;</a></li>
	    {% else %}
	      <li class="disabled paginate-active"><span>&laquo;</span></li>
	    {% endif %}
	    {% for i in sublist.paginator.page_range %}
	      {% if sublist.number == i %}
	        <li class="active paginate-active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
	      {% else %}
	        <li class="paginate-inactive"><a class="text-white" href="?page={{ i }}">{{ i }}</a></li>
	      {% endif %}
	    {% endfor %}
	    {% if sublist.has_next %}
	      <li class="paginate-inactive"><a class="text-white" href="?&page={{ sublist.next_page_number }}">&raquo;</a></li>
	    {% else %}
	      <li class="disabled paginate-active"><span>&raquo;</span></li>
	    {% endif %}
	  </ul>
	{% endif %}

  </div>
</section>

{% endblock %}

comparator/templates/comparator/index.html
{% extends 'comparator/base.html' %}
{% load static %}

{% block content %}
<!-- Masthead -->
<header class="masthead masthead-img">
  <div class="container h-100">
    <div class="row h-100 align-items-center justify-content-center text-center">
      <div class="col-lg-10 align-self-end">
        <h1 class="text-uppercase text-white font-weight-bold">Du gras, oui, mais de qualité !</h1>
        <hr class="divider my-4">
      </div>
      <div class="col-lg-8 align-self-baseline">
        <h4 class="text-white mb-5">Trouvez un produit de substitution pour ceux que vous consommez tous les jours.</h4>
        <form method='get' action="{% url 'comparator:search' %}">
          {% csrf_token %}
          {{ form }}
          <button type="submit" class="search-button btn btn-primary btn-xl js-scroll-trigger">Chercher</button>
        </form>
      </div>
    </div>
  </div>
</header>

<!-- About Section -->
<section class="page-section bg-primary">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-8 text-center">
        <h2 class="text-white mt-0">Colette et Rémy</h2>
        <hr class="divider light my-4">
        <p class="text-white-80 mb-4">Remy et Colette sont amoureux de la gastronomie française (on ne peut les blâmer !). Travaillant quotidiennement avec les meilleurs produits du terroir, ils affectionnent particulièrement la bonne chaire et aiment partager leur passion. Il est donc normal que Remy ait sauté au plafond quand Colette, un jour de déprime, sortit du placard un kilo de Nutella et l’attaqua à la petite cuillère. Pourquoi ne pas opter pour une pâte à tartiner aux noisettes, plus consistante et moins sucrée ? Pourquoi, oh pourquoi s’infliger une telle souffrance ? Rémy était sidéré. La réponse de Colette fut simple : elle n’avait pas trouvé de substitut assez convainquant. A vrai dire, elle n’avait même pas cherché.<br><br>Tous deux se souvinrent alors que nombre de leurs clients leur avaient compté, entre deux verres, qu’il était difficile de trouver des substituts aux cochonneries que nous mangions dès le petit déjeuner. Pourquoi ne pas lancer une plateforme web en ce sens ? Voici votre mission !</p>
        <div class="row">
          <div class="col-lg-6 text-center">
            <img class="char-pic" src="{% static 'comparator/img/colette.png' %}" alt="">
            <h4 class="text-white mt-0">Colette</h4>
          </div>
          <div class="col-lg-6 text-center">
            <img class="char-pic" src="{% static 'comparator/img/ratatouille.png' %}" alt="">
            <h4 class="text-white mt-0">Rémy</h4>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- Contact Section -->
<section class="page-section bg-contact" id="contact">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-8 text-center">
        <h2 class="mt-0">Contactez-nous !</h2>
        <hr class="divider my-4">
      </div>
    </div>
    <div class="row">
      <div class="col-lg-4 ml-auto text-center mb-5 mb-lg-0">
        <i class="fas fa-phone fa-3x mb-3 text-muted"></i>
        <div>00 11 22 33 44</div>
      </div>
      <div class="col-lg-4 mr-auto text-center">
        <i class="fas fa-envelope fa-3x mb-3 text-muted"></i>
        <!-- Make sure to change the email address in anchor text AND the link below! -->
        <a class="font-orange d-block" href="mailto:contact@yourwebsite.com">contact@purbeurre.com</a>
      </div>
    </div>
  </div>
</section>

{% endblock %}

comparator/templates/comparator/login.html
{% extends 'comparator/base.html' %}
{% load static %}

{% block content %}

{% if not request.user.is_authenticated %}
<header class="masthead connect-img">
  <div class="container h-100">
    <div class="row h-100 align-items-center justify-content-center text-center">
      <div class="col-lg-10 align-self-end">
        <h1 class="text-uppercase text-white font-weight-bold">Connexion au compte utilisateur</h1>
        <hr class="divider my-4">
      </div>
      <div class="col-lg-8 align-self-baseline">
        <form method="post">
          {% csrf_token %}
          <ul class="connect-list">
            {{ form.as_ul }}
            {{ error_message }}
          	<li class="connect-list-row"><button id='submit-button' type="submit" class="mytest btn btn-primary btn-xl js-scroll-trigger">Valider</button></li>
          </ul>
        </form>
        <div>
          <a class="text-uppercase text-white font-weight-bold" href="{% url 'user:create_user' %}">Créer un compte utilisateur</a>
        </div>
      </div>
    </div>
  </div>
</header>
{% else %}
<header class="masthead connect-img">
  <div class="container h-100">
    <div class="row h-100 align-items-center justify-content-center text-center">
      <div class="col-lg-10 align-self-end">
        <h1 class="text-uppercase text-white font-weight-bold">Connexion réussie</h1>
        <hr class="divider my-4">
      </div>
      <div class="col-lg-8 align-self-baseline">
      	<h1 class="text-uppercase text-white font-weight-bold">Bienvenue {{ request.user }}</h1>
      </div>
    </div>
  </div>
</header>

{% endif %}

{% endblock %}

comparator/templates/comparator/search.html
{% extends 'comparator/base.html' %}
{% load static %}

{% block content %}

<section class="page-section bg-beige sect-h-100">
  <div class="container h-0">
    <div class="row h-100 align-items-center justify-content-center text-center">
      <div class="col-lg-12 align-self-end">
        <h3 class="text-uppercase text-white font-weight-bold">Votre recherche : {{ user_input }}</h3>
        <hr class="divider my-4">
      </div>
    </div>
    {% if food|length_is:"0" %}
    	<h4 class="text-uppercase text-center text-white font-weight-bold">Aucun résultat de recherche</h4>
    {% else %}
    <div class="container">
	    <div class="row">
		  {% for item in food %}
			  <div class="col-sm-4 text-center food-item-box"><span class="nutriscore" data-score="{{ item.nutriscore }}">{{ item.nutriscore }}</span>
			  	<div class="food-item">
			  	  <div style="background-image: url('{{ item.pict }}');background-size: cover;background-position: 0px 50%;height: 85%;border-top-left-radius: 5px;border-top-right-radius: 5px;"></div>
			  	  <button class="subs-button2 btn btn-primary btn-xl cap-text" onclick="window.location.href = '{% url 'comparator:detail' bar_code=item.code %}';">{{ item.name }}</button>
			  	  <form method="get" action="{% url 'comparator:substitute' %}">
			  	  	<input type="text" name="user_substitute" class="hidden-field" value="{{ item.code }}">
				  	<button type="submit" class="subs-button btn btn-primary btn-xl cap-text">Trouver un substitut</button>
				  </form>
			    </div>
			  </div>
		  {% endfor %}
	    </div>
	</div>
    {% endif %}
      <div class="clearfix"></div>

    {% if food.has_other_pages %}
	  <ul class="pagination">
	    {% if food.has_previous %}
	      <li class="paginate-inactive"><a class="text-white" href="?user_input={{ user_input }}&page={{ food.previous_page_number }}">&laquo;</a></li>
	    {% else %}
	      <li class="disabled paginate-active"><span>&laquo;</span></li>
	    {% endif %}
	    {% for i in food.paginator.page_range %}
	      {% if food.number == i %}
	        <li class="active paginate-active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
	      {% else %}
	        <li class="paginate-inactive"><a class="text-white" href="?user_input={{ user_input }}&page={{ i }}">{{ i }}</a></li>
	      {% endif %}
	    {% endfor %}
	    {% if food.has_next %}
	      <li class="paginate-inactive"><a class="text-white" href="?user_input={{ user_input }}&page={{ food.next_page_number }}">&raquo;</a></li>
	    {% else %}
	      <li class="disabled paginate-active"><span>&raquo;</span></li>
	    {% endif %}
	  </ul>
	{% endif %}

  </div>
</section>

{% endblock %}

comparator/templates/comparator/substitute.html
{% extends 'comparator/base.html' %}
{% load static %}


{% block content %}

<section class="page-section-7" style="background-image: url('{{ query.pict }}');background-size: cover;background-repeat: no-repeat;background-position: 0 50%;">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-8 text-center">
        <h2 class="text-white mt-0 food-name" id="user_query">{{ query.name }}</h2>
      </div>
    </div>
  </div>
</section>

<section class="page-section bg-beige sect-h-100">
    <div class="container">
	    <div class="row">

			  {% for key, value in subdic.items %}
			  <div class="col-sm-4 text-center food-item-box"><span class="nutriscore" data-score="{{ key.nutriscore }}">{{ key.nutriscore }}</span>
			  	<div class="food-item">
			  	  <div style="background-image: url('{{ key.pict }}');background-size: cover;background-position: 0px 50%;height: 85%;border-top-left-radius: 5px;border-top-right-radius: 5px;"></div>
			  	  <button class="subs-button2 btn btn-primary btn-xl cap-text" onclick="window.location.href = '{% url 'comparator:detail' bar_code=key.code %}';">{{ key.name }}</button>
			  	  {% if request.user.is_authenticated %}
			  	  	{% if value == True %}
				  	  	<form method="get" action="{% url 'comparator:delete_sub' %}">
				  	  		<input type="text" name="query_code" class="hidden-field" value="{{ query.code }}">
				  	  		<input type="text" name="del_sub" class="hidden-field" value="{{ key.code }}">
				  	  		<button id="func-test" class="subs-button btn btn-primary btn-xl cap-text saved_fav">Déja en favoris</button>
				  	  	</form>
			  	  	{% else %}
				  	  	<form method="get" action="{% url 'comparator:save_sub' %}">
					  	  	<input type="text" name="query_code" class="hidden-field" value="{{ query.code }}">
					  	  	<input type="text" name="sub_code" class="hidden-field" value="{{ key.code }}">
						  	<button type="submit" class="subs-button btn btn-primary btn-xl cap-text">Ajouter aux favoris</button>
						</form>
					{% endif %}
				  {% else %}
				    <button class="subs-button btn btn-primary btn-xl cap-text" onclick="window.location.href = '{% url 'user:connexion' %}';">Ajouter aux favoris</button>
				  {% endif %}
			    </div>
			  </div>
		  {% endfor %}
	    </div>
	</div>
  </div>
</section>

{% endblock %}